### ISSUE TITLE
Version 2.1.0 for 1.20.1?

### ISSUE THREAD

**Issue by Xandriz** [AleGuzAva/EEssentials#32]
This is more of a request than an issue since having the new features for 1.20.1 would be amazing.

**Comment by AleGuzAva** [comment]
Hello there! I mentioned this in my discord, but I'll paste the message here:

# Notice
With 1.21 already being out, I have made the decision to fully focus on EEssentials for 1.21, and drop support for 1.20.1

As many of y'all may have seen, EEssentials updates pretty much halted after 1.1.0, and this is mainly due to how much busier I've gotten since June. It is currently really demanding for me to work on maintaining both a 1.20.1 version and a 1.21 version, so I hope you all understand the decision I've made.

Thanks for using EEssentials!

As this is a volunteer project, it isn't feasible for me to maintain two separate MC versions given my schedule.
